import Head from "next/head";

export default function Seo({ content }: { content: string }) {
	return <Head>
		<title>Kyubong | {content}</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/favicon.ico" />
	</Head>
}